theme = "focus_nova"

[editor]
line-number = "relative"
cursorline = true
color-modes = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.indent-guides]
render = true

[keys.normal]
C-right = "move_next_word_start"
C-left = "move_prev_word_end"

[keys.insert]
C-right = "move_next_word_start"
C-left = "move_prev_word_end"
